# Set project name
name: htmx-books-prod

services:
  web:
    # Specify the ./app directory containing the Dockerfile.prod for building the image
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    # Run the Gunicorn server
    command: gunicorn django_htmx.wsgi:application --bind 0.0.0.0:8000
    # Map port 8000 of the container to port 8000 of localhost (127.0.0.1:8000)
    ports:
      - 127.0.0.1:8000:8000
    # File containing environment variables for the container
    env_file:
      - .env.prod
    # Wait for the db and memcached containers to start
    depends_on:
      - db
      - memcached

  db:
    # Use the PostgreSQL version 15 image
    image: postgres:14
    # Mount the postgres-data volume to the /var/lib/postgresql/data directory of the db container
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # File containing environment variables for the container
    env_file:
      - .env.prod
    # Use environment variable values from the .env.prod file
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

  memcached:
    # Use the Memcached version 1.6.21 image
    image: memcached:1.6.21


  nginx:
    # Specify the ./nginx directory containing the Dockerfile for building the image
    build: ./nginx
    # Mount the static-data volume to the /home/app/web/static directory of the nginx container
    volumes:
      - static-data:/home/app/web/static

    # Map port 80 of the container to port 80 of the local machine (the port will be accessible externally)
    ports:
      - 80:80
    # Wait for the web container to start
    depends_on:
      - web

volumes:
  # Declare the postgres-data volume for storing PostgreSQL data
  postgres-data:
  # Declare the static-data volume for storing static files
  static-data:
